### PR TITLE
feat: minimal change to test custom network

### LINKED ISSUE #1900: I would like the client to update security parameters when updating the addressbook so that updates will affect TLS
### Problem

I'd like to test using TLS with a network other than {mainnet, testnet, previewnet}.

### Solution

- Have `Client::setNetworkFromAddressBook` update the `Network::addressBook` and `Node::addressBookEntry` which contain the security parameters.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by matteriben**
**Description**:
A minimal change to allow testing a custom network.

Allows testing a custom network, though not nearly as nicely as PR #1901. This change allows for additional ledger IDs without relying on split package access to package-private methods.

**Related issue(s)**:

Fixes #1900

### CODE REVIEW

**Comment by thenswan** [comment]
Hey @matteriben,

I discussed your request and your proposed changes with a team, we appreciate and respect your work, and think that we should schedule time in our sprint to do a deeper review and respond with enhancements to your approaches or consider alternatives that would satisfy your use case and align with our expectations, as for example in PR #1901 there are couple concerns:
- `NodeAddressBook.fromProtobuf` is package protected and not intended for usage by SDK clients;
- Objects from `com.hedera.hashgraph.sdk.proto` package are open for clients, but anyway SDK clients shouldn’t use them as this might be changed.

Current PR opens something new for SDK clients, which wasn't available before.

Can you please give more info:
- I understood that you would like to set up a `Client` using `TLS` with a network other than `mainnet`, `testnet`, `previewnet`, but more info on what and how you would like to achieve would be really helpful;
- If you're trying to test something, i.e. use this feature temporary or you're planning to use it long-term, like in production dApp (as if you need it short-term, we might consider to release a `beta` version for you).

**Comment by matteriben** [comment]
> Can you please give more info:
> 
> * I understood that you would like to set up a `Client` using `TLS` with a network other than `mainnet`, `testnet`, `previewnet`, but more info on what and how you would like to achieve would be really helpful;
> * If you're trying to test something, i.e. use this feature temporary or you're planning to use it long-term, like in production dApp (as if you need it short-term, we might consider to release a `beta` version for you).

Yes, that's right. I'd like to use `Client` with `TLS` on a custom network.

A beta release version with support for this would be helpful for me for now, but honestly, I see the need to support additional custom networks increasing in the future.

**Comment by matteriben** [comment]
> as for example in PR #1901 there are couple concerns:
> 
> * `NodeAddressBook.fromProtobuf` is package protected and not intended for usage by SDK clients;

I updated PR #1901, the example in the test case no longer uses `NodeAddressBook.fromProtobuf`.

**Comment by matteriben** [comment]
@thenswan

> ... as for example in PR #1901 there are couple concerns:
> 
> * `NodeAddressBook.fromProtobuf` is package protected and not intended for usage by SDK clients;

I updated PR #1901, the example in the test case no longer uses `NodeAddressBook.fromProtobuf`.

> Can you please give more info:
> 
> * I understood that you would like to set up a `Client` using `TLS` with a network other than `mainnet`, `testnet`, `previewnet`, but more info on what and how you would like to achieve would be really helpful;
> * If you're trying to test something, i.e. use this feature temporary or you're planning to use it long-term, like in production dApp (as if you need it short-term, we might consider to release a `beta` version for you).

Yes, that's right. I'd like to use `Client` with `TLS` on a custom network.

A beta release version with support for this would be helpful for me for now, but honestly, I see the need to support additional custom networks increasing in the future.

**Comment by thenswan** [comment]
@matteriben hey, we decided to release beta for you, can you please include features that you would like to have in one PR and let me know what PR that will be 🙂

**Comment by matteriben** [comment]
> ... we should schedule time in our sprint to do a deeper review and respond with enhancements to your approaches or consider alternatives ...

Please keep me updated, and let me know if I can help.

> ... we decided to release beta for you.

Thank you, but currently I have a workaround and don't require a beta release.

**Comment by SimiHunjan** [comment]
Another PR exists for the same issue #1900

**Comment by matteriben** [comment]
@thenswan The purpose of this change was to allow for LedgerId to be extended such that I could arrange for an `addressbook.pb` file corresponding to my custom network be read by the classloader at runtime. I consider this a bit more of a hack then PR #1901.

**Pull request closed without merging**
