### PR TITLE
chore: bump com.google.protobuf:protoc dependency

### LINKED ISSUE #1910: Bump protoc dependency
**The problem**
`com.google.protobuf:protoc` dependency was downgraded after #1732. Also, before these changes, I noticed that some version of this dependency broke `sdk-full`, so a workaround was applied (#1808).

**The solution**
- investigate which version of `com.google.protobuf:protoc` dependency starts to introduce breaking changes
- update the dependency
- leave a comment, so it will be clear that this dependency shouldn't be updated for now

### PR DESCRIPTION
**Pull request by thenswan**
**Description**:
This PR bumps `com.google.protobuf:protoc` dependency and adds a comment for it.

Closes #1910

### CODE REVIEW

**Review by agadzhalov — DISMISSED** [review]
LGTM

**Review by jjohannes — COMMENTED** [review]
The same version is also used in two more places:
- https://github.com/hashgraph/hedera-sdk-java/blob/main/sdk-dependency-versions/build.gradle.kts#L34
- https://github.com/hashgraph/hedera-sdk-java/blob/main/sdk-dependency-versions/build.gradle.kts#L37

Should these be updated as well?

(Note: it would probably be great to get rid of the duplication in the future, but that's a different problem)

**Comment by thenswan** [comment]
Thank you @jjohannes, I updated them as well

**Review by jjohannes — APPROVED** [review]
Looks like two unit tests assertions needs to be updated:
https://scans.gradle.com/s/gdjcfr2wqsav2/tests/overview?outcome=FAILED

**Review by jjohannes — APPROVED** [review]

**Review by 0xivanov — APPROVED** [review]

**Pull request merged**
