### PR TITLE
Make testEnv implement Autoclosable Interface, replace occurrences

### PR DESCRIPTION
**Pull request by steffenboe**
**Description**:
Makes `IntegrationTestEnv` implement Autoclosable and replaces occurrences in tests with `try-with-resources`-block.

**Related issue(s)**:

Fixes #
#1975 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by steffenboe** [comment]
need to take a look at the indentation changes yet, so i switched this PR to WIP

**Comment by steffenboe** [comment]
ready for review!

**Review by 0xivanov — COMMENTED** [review]
Hey, nice work!
DCO check is failing because the commits are not signed off. Please check out https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md and see how to set up your GPG keys. 
When you've setup the keys you can rebase your commits while signing them.

**Review by 0xivanov — COMMENTED** [review]
Looks good, there are some usages missing thought, like in `TokenGrantKycIntegrationTest` and `TransactionResponseTest`

**Comment by steffenboe** [comment]
you're correct, and these tests aren't the only ones where a replacement is not possible. this is because the close()-method gets called with parameters there. this is not conforming to the Autoclosable interface, and so these occurrences can't be replaced with a `try-with-resources` block.

**Comment by 0xivanov** [comment]
@steffenboe You are right, I had forgotten about that! I was actually thinking a while back to rework the `close` method to not have overloads and remove the wiping logic `wipeAccountHbars(newAccountId, newAccountKey);` . This additional logic is making the github action slow and we don't need it since the operator we are using in the `local-node` has 10k HBARs which should be enough.

Would you like to rework the `close` method to look something like this? :
```java
    public void close() throws Exception {
        if (!operatorId.equals(originalClient.getOperatorAccountId())) {
            var hbarsBalance = new AccountBalanceQuery()
                .setAccountId(operatorId)
                .execute(originalClient)
                .hbars;
            new TransferTransaction()
                .addHbarTransfer(operatorId, hbarsBalance.negated())
                .addHbarTransfer(Objects.requireNonNull(originalClient.getOperatorAccountId()), hbarsBalance)
                .freezeWith(originalClient)
                .signWithOperator(client)
                .execute(originalClient);
            client.close();
        }

        originalClient.close();
    }
```

And then you could finish the rest of the tests to use `try-with-resources`.

**Comment by steffenboe** [comment]
Sounds good! Will work on that ;)

**Review by 0xivanov — APPROVED** [review]
LGTM, TY @steffenboe

**Pull request merged**
