### PR TITLE
execute*Async(): provide overloads that pass `this` for context

### PR DESCRIPTION
**Pull request by abonander**
cc @mike-burrage-hedera @mehcode

### CODE REVIEW

**Comment by abonander** [comment]
I need to add this to `Transaction` as well, hang on.

**Comment by abonander** [comment]
Fixed.

**Comment by mehcode** [comment]
@mike-burrage-hedera does this address what you were looking for?

**Comment by mike-burrage-hedera** [comment]
That'll work (having access to the transaction on error).

**Pull request merged**
